# <#noparse>
# The configuration supports the use of freemarker templates as follows:
#
# ${PORT!8080}
# -> Uses the value of the PORT environment variable.
#    If the variable is not set, 8080 is used as default.
#
# ${dbprops.user!root}
# -> Uses the value of the "user" property from the "db.properties" file.
#    If the variable is not set, "root" is used as default.
#    ("dbprops" refers to "db.properties")
#
# </#noparse> (-> tells freemarker to ignore all freemarker expression in the comment above)

#------------------------------------------------------------
# General Server Configuration 
#------------------------------------------------------------

server:
  # JAX-RS resources are served from "/api/*"
  # (asset bundle by default serves assets from "/*")
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 80
  adminConnectors:
    - type: http
      port: 8081

logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  loggers:
    de.ustutt.iaas.cc: DEBUG
  appenders:
    # write log to console
    - type: console

# swagger configuration
swagger:
  resourcePackage: de.ustutt.iaas.cc.resources

#------------------------------------------------------------
# Notebook App Configuration 
#------------------------------------------------------------

# sets the ID of this service instance, optional
serviceInstanceID: My first Notebook App

textProcessor:
  # local, remoteSingle, remoteMulti, queue 
  mode: local

notesDB:
  # tmp, jdbc, gcds
  # tmp = non-persistent in-memory
  # jdbc = SQL database, requires JDBC database configuration (http://www.dropwizard.io/1.1.0/docs/manual/jdbi.html)
  # gcds = google cloud datastore
  mode: tmp